<a href="https://colab.research.google.com/github/tobiartinian/Econom-a-y-Finanzas/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import duckdb
%pip install jupysql
%pip install duckdb-engine
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%sql duckdb://

Requirement already satisfied: jupysql in /usr/local/lib/python3.13/dist-packages (0.11.1)
Requirement already satisfied: prettytable>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.18.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (from jupysql) (2.0.52)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.6.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.13/dist-packages (from jupysql) (25.20.2)
Requirement already satisfied: jupysql-plugin>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.4.5)
Requirement already satisfied: ploomber-core>=0.2.7 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.2.27)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Requirement already satisfied: posthog>=3.0 in /usr/local/lib/python3.13/dist-packages (from ploomber-core>=0.2.7->jupysql) (7.53.0)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=3.12.0->jupysql) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->jupysql) (3.0.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->jupysql) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->jupysql) (4.16.0)
Requirement already satisfied: requests<3.0,>=2.7 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.4)
Requirement already satisfied: backoff>=1.10.0 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2026.7.22)
Requirement already satisfied: duckdb-engine in /usr/local/lib/python3.13/dist-packages (0.17.0)
Requirement already satisfied: duckdb>=0.5.0 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (1.3.2)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (26.3)
Requirement already satisfied: sqlalchemy>=1.3.22 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (2.0.52)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (4.16.0)
The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [8]:
dataset_path = "/content/drive/MyDrive/Economía y finanzas/"
dataset_file = "competencia_01.csv"

##EDA

In [9]:
%%sql
create or replace table competencia_01 as
select
    *
from read_csv_auto("{{dataset_path + dataset_file}}")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [Success]
Index: []

In [11]:
%%sql
select DISTINCT(foto_mes)
from competencia_01
order by foto_mes ASC
# tenemos info desde marzo 21 a agosto 21

   foto_mes
0    202103
1    202104
2    202105
3    202106
4    202107
5    202108

In [17]:
%%sql
SELECT
AVG(active_quarter) AS tasa_activacion,
foto_mes
FROM competencia_01
GROUP BY foto_mes

   tasa_activacion  foto_mes
0         0.985734    202103
1         0.986876    202104
2         0.987275    202105
3         0.987722    202106
4         0.987478    202107
5         0.986632    202108

In [20]:
%%sql
SELECT
clase_ternaria,
AVG(active_quarter) as tasa_activacion
FROM competencia_01
GROUP BY clase_Ternaria
ORDER BY tasa_activacion DESC

  clase_ternaria  tasa_activacion
0       CONTINUA         0.988621
1           None         0.987453
2         BAJA+2         0.859848
3         BAJA+1         0.844733

In [28]:
%%sql
SELECT
    clase_ternaria,
    COUNT(*) AS cantidad_vip,
    PRINTF('%.2f%%', COUNT(*) * 100.0 / SUM(COUNT(*)) OVER()) AS porcentaje_vip
FROM competencia_01
WHERE cliente_vip = 1
GROUP BY clase_ternaria
ORDER BY cantidad_vip DESC;

  clase_ternaria  cantidad_vip porcentaje_vip
0       CONTINUA          2200         70.69%
1           None           905         29.08%
2         BAJA+1             4          0.13%
3         BAJA+2             3          0.10%