<a href="https://colab.research.google.com/github/tobiartinian/Econom-a-y-Finanzas/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import duckdb
%pip install jupysql
%pip install duckdb-engine
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%sql duckdb://

Collecting jupysql
  Downloading jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: prettytable>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.18.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (from jupysql) (2.0.52)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.6.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in /usr/local/lib/python3.13/dist-packages (from jupysql) (0.2.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from jupysql) (3.1.6)
Requirement already satisfied: sqlglot>=11.3.7 in /usr/local/lib/python3.13/dist-packages (from jupysql) (25.20.2)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Downloading jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Downloading ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-7.53.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=3.12.0->jupysql) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->jupysql) (3.0.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->jupysql) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->jupysql) (4.16.0)
Requirement already satisfied: requests<3.0,>=2.7 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.4)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2026.7.22)
Downloading jupysql-0.11.1-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 3.1 MB/s eta 0:00:00
Downloading jupysql_plugin-0.4.5-py3-none-any.whl (192 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.8/192.8 kB 6.3 MB/s eta 0:00:00
Downloading ploomber_core-0.2.27-py3-none-any.whl (22 kB)
Downloading posthog-7.53.0-py3-none-any.whl (662 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 662.8/662.8 kB 15.1 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Installing collected packages: backoff, posthog, ploomber-core, jupysql-plugin, jupysql
Successfully installed backoff-2.2.1 jupysql-0.11.1 jupysql-plugin-0.4.5 ploomber-core-0.2.27 posthog-7.53.0
Collecting duckdb-engine
  Downloading duckdb_engine-0.17.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: duckdb>=0.5.0 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (1.3.2)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (26.3)
Requirement already satisfied: sqlalchemy>=1.3.22 in /usr/local/lib/python3.13/dist-packages (from duckdb-engine) (2.0.52)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy>=1.3.22->duckdb-engine) (4.16.0)
Downloading duckdb_engine-0.17.0-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 3.7 MB/s eta 0:00:00
Installing collected packages: duckdb-engine
Successfully installed duckdb-engine-0.17.0

In [2]:
dataset_path = "/content/drive/MyDrive/Economía y finanzas/"
dataset_file = "competencia_01.csv"

##EDA

In [3]:
%%sql
create or replace table competencia_01 as
select
    *
from read_csv_auto("{{dataset_path + dataset_file}}")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Empty DataFrame
Columns: [Success]
Index: []

In [5]:
%%sql
select DISTINCT(foto_mes)
from competencia_01
order by foto_mes ASC
# tenemos info desde marzo 21 a agosto 21

   foto_mes
0    202103
1    202104
2    202105
3    202106
4    202107
5    202108

In [ ]:
%%sql
SELECT
AVG(active_quarter) AS tasa_activacion,
foto_mes
FROM competencia_01
GROUP BY foto_mes

   tasa_activacion  foto_mes
0         0.985734    202103
1         0.986876    202104
2         0.987275    202105
3         0.987722    202106
4         0.987478    202107
5         0.986632    202108

In [ ]:
%%sql
SELECT
clase_ternaria,
AVG(active_quarter) as tasa_activacion
FROM competencia_01
GROUP BY clase_Ternaria
ORDER BY tasa_activacion DESC

  clase_ternaria  tasa_activacion
0       CONTINUA         0.988621
1           None         0.987453
2         BAJA+2         0.859848
3         BAJA+1         0.844733

In [ ]:
%%sql
SELECT
    clase_ternaria,
    COUNT(*) AS cantidad_vip,
    PRINTF('%.2f%%', COUNT(*) * 100.0 / SUM(COUNT(*)) OVER()) AS porcentaje_vip
FROM competencia_01
WHERE cliente_vip = 1
GROUP BY clase_ternaria
ORDER BY cantidad_vip DESC;

  clase_ternaria  cantidad_vip porcentaje_vip
0       CONTINUA          2200         70.69%
1           None           905         29.08%
2         BAJA+1             4          0.13%
3         BAJA+2             3          0.10%

In [ ]:
%%sql
SELECT
  PRINTF('%.2f%%',AVG(internet)*100) as tasa_internet
FROM competencia_01

  tasa_internet
0         4.91%

In [8]:
%%sql
SELECT
  clase_ternaria,
  PRINTF('%.2f%%',AVG(internet)*100) as tasa_internet
FROM competencia_01
GROUP BY clase_ternaria

  clase_ternaria tasa_internet
0           None         3.50%
1         BAJA+2        20.19%
2       CONTINUA         5.47%
3         BAJA+1        13.09%

In [11]:
%%sql
SELECT
AVG(cliente_edad) as avg_edad,
MAX(cliente_edad) as max_edad,
MIN(cliente_edad) as min_edad,
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY cliente_edad) AS mediana_edad
FROM competencia_01

    avg_edad  max_edad  min_edad  mediana_edad
0  46.884686       101        18          45.0

In [28]:
%%sql
WITH base AS (
    SELECT
        numero_de_cliente,
        clase_ternaria,
        CASE
            WHEN cliente_edad < 30 THEN '1. Menor a 30'
            WHEN cliente_edad < 40 THEN '2. 30 a 39'
            WHEN cliente_edad < 50 THEN '3. 40 a 49'
            WHEN cliente_edad < 60 THEN '4. 50 a 59'
            ELSE '5. 60 o más'
        END AS rango_edad
    FROM competencia_01
)
SELECT
    rango_edad,
    clase_ternaria,
    -- Porcentaje sobre el TOTAL GLOBAL de la tabla
    ROUND(100.0 * COUNT(DISTINCT numero_de_cliente) / SUM(COUNT(DISTINCT numero_de_cliente)) OVER(), 2) AS pct_sobre_total_global,
    ROUND(100.0 * COUNT(DISTINCT numero_de_cliente) / SUM(COUNT(DISTINCT numero_de_cliente)) OVER(PARTITION BY rango_edad), 2) AS pct_sobre_total_rango,
FROM base
GROUP BY rango_edad, clase_ternaria
ORDER BY rango_edad, clase_ternaria;

,rango_edad,clase_ternaria,pct_sobre_total_global,pct_sobre_total_rango
0,1. Menor a 30,BAJA+1,0.11,1.50
1,1. Menor a 30,BAJA+2,0.09,1.24
2,1. Menor a 30,CONTINUA,3.55,49.97
3,1. Menor a 30,None,3.36,47.29
4,2. 30 a 39,BAJA+1,0.37,1.45
5,2. 30 a 39,BAJA+2,0.31,1.19
6,2. 30 a 39,CONTINUA,12.73,49.36
7,2. 30 a 39,None,12.37,47.99
8,3. 40 a 49,BAJA+1,0.39,1.33
9,3. 40 a 49,BAJA+2,0.30,1.04
10,3. 40 a 49,CONTINUA,14.28,49.17
11,3. 40 a 49,None,14.08,48.46
12,4. 50 a 59,BAJA+1,0.27,1.35
13,4. 50 a 59,BAJA+2,0.21,1.05
14,4. 50 a 59,CONTINUA,9.74,49.11
15,4. 50 a 59,None,9.62,48.49
16,5. 60 o más,BAJA+1,0.34,1.89
17,5. 60 o más,BAJA+2,0.28,1.51
18,5. 60 o más,CONTINUA,8.81,48.33
19,5. 60 o más,None,8.80,48.27